In [1]:
import numpy as np

In [1]:
a = [10,11,12,13,14,15]

In [6]:
n_a = np.array(a)

In [3]:
import numpy as np

In [4]:
n_a = np.array(a)

In [7]:
n_a

array([10, 11, 12, 13, 14, 15])

In [8]:
n_a[0]

10

In [9]:
n_a[1]

11

In [10]:
n_a[0:3]

array([10, 11, 12])

In [11]:
n_a[2,4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [12]:
n_a[2:4]

array([12, 13])

In [13]:
np.average(n_a)

12.5